DROP TABLE IF EXISTS server;
DROP TABLE IF EXISTS rack;

CREATE TABLE rack
(
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed  TIMESTAMP NOT NULL,
    size     INTEGER   NOT NULL DEFAULT 0,
    capacity INTEGER   NOT NULL
);

CREATE TABLE server
(
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed TIMESTAMP NOT NULL,
    rack_id INTEGER   NOT NULL,
    FOREIGN KEY (rack_id) REFERENCES rack (id)
);

INSERT INTO rack (id, changed, size, capacity)
VALUES (1, CURRENT_TIMESTAMP, 2, 10);
